# Generated by Django 5.1.5 on 2025-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], default='work', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='due_dtae',
            field=models.DateTimeField(default=None),
        ),
    ]
