# Generated by Django 5.1.5 on 2025-02-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_due_dtae_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
